# https://news.ycombinator.com/item?id=32970198
name: ci
on:
  pull_request: null
  push:
    branches: [main]
env:
  CARGO_INCREMENTAL: 0
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Cache rust
        uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: cargo test
